### ISSUE TITLE
Remove "py" from name

### ISSUE THREAD

**Issue by EpicWink** [bobfang1992/pytomlpp#1]
Having "py" in the name of a Python package is redundant. I suggest another name like `tomlpp` or `tomlplusplus`

**Comment by bobfang1992** [comment]
Definitely see where you are coming from. My main concern is that if we simply call it tomlplusplus then it will clash with the original cpp project, that's why I added py prefix. I guess we can name it simply tomlpp but that sounds like a cpp project to me as a lot of cpp projects are named that way. Let me ponder on this and see if I can find a better name.

**Comment by EpicWink** [comment]
Sorry, I meant just for the distributed Python package. The repository name is completely up to you, and I think pytomlpp is fine. If anything, I'd add more Python: make the repo name "python-tomlpp" or something, but again, up to you.
