### ISSUE TITLE
Test with 1.0-rc1 TOML spec tests

### ISSUE THREAD

**Issue by EpicWink** [bobfang1992/pytomlpp#23]
https://github.com/iarna/toml-spec-tests, see https://github.com/bobfang1992/pytomlpp/issues/20#issuecomment-647534319

**Comment by marzer** [comment]
OK, here's an update about conformance. I've spent the last few days bringing the tests from both test sets into the `toml++` test suite, and fixed a number of small conformance bugs I identified in the process. You should be able to update your test code to remove the exceptions for the following **invalid** inputs:
- `BurntSushi/float-leading-zero`
- `BurntSushi/float-leading-zero-neg`
- `BurntSushi/float-leading-zero-pos`
- `BurntSushi/float-no-leading-zero`
- `BurntSushi/float-no-trailing-digits`

The fact that they were previously failing was an error on my part; I was too relaxed with allowing omission of some digits in float values.

Additionally, you should _add_ an exception to exclude `BurntSushi/datetime` from the set of **valid** inputs because the test data itself is incorrect (see [here](https://github.com/BurntSushi/toml-test/issues/58)).

Finally, since I've also added in tests for the TOML 1.0.0 spec from iarna's suite, you might want to re-evaluate if you even need to bother since it might be a bit of work (and is all about to be replaced with the official `toml-lang/conformance` anyway). If you _do_ want to, there's a few exceptions you'll need to add to the **invalid** cases because they ignore the TOML spec's provision for sub-millisecond precision in fractional time values, thus making them incorrect:
- `iarna/spec-date-time-6`
- `iarna/spec-date-time-local-2`
- `iarna/spec-time-2`

(more info [here](https://github.com/iarna/toml-spec-tests/issues/3))

The latest `toml++` in master contains all the conformance fixes, so update at your leisure ^_^

**Comment by bobfang1992** [comment]
Hey, thanks for this. I will update the library soon. I think I will still try to include both test suite in this repo and I will add more unit tests on my side to improve the quality of this repo.

**Comment by bobfang1992** [comment]
Hi, thanks for the input. I will keep what we have for now and later change it to the merged conformance tests. I am now updating `toml++` and said tests.

**Comment by bobfang1992** [comment]
closed via 54add69dfd9f56ac86669ec0badd042ad698bb79
